language: ruby
git:
  depth: 1
rvm:
- 2.5.0
script:
- bin/rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: YLM/BiQPu0GMgns2tUeE1qO58JmzRVfo20ebgG6XNBqmptzPI3ReqEs/bYaUSdygYiK81pVhy69dWj3bjKjWV6C7EBr/w6tOE+qM6PUKEvd8rlcviXXUOgFfMCLLqREYi21zr+I0Z1Gj8mCRklBV2DFF+f6TTIcSh/afYVVWv8rktpMgivijB9Cexek5gP/8zhg8AaKAnGBzrmKzxraKZA7s97e5iWvZBMLtrDyqSe8mfkviKeOE6B1sKb8YdYLh9fSSpNewOEzKTtgS2AWmoCdP6IiUk+dhORTHu0s13Rz+nD2ZOYfkYIXt6iMNYlFHB30Nm1/4iusCrStIphDXlLqCD6DfBX4gRmBgRHsceCHoHggWqOCbgz28MI1vtkFsnoLz7/fJBlpPy/g+7VC6SnSt5fux35W4u26QcvMwmD3MkwJmjjktsi+GlIF9D+oDtb79VTUM1hzT2kkByWATZJnUK9M3CxxzGe4CqXpeFpVW5d0K84aMd0jpAuKFZf87jOVtQ80Jtl/ANFpHP/LO8P/SUil4OZh2eKmIADZg/z6itytkK/lcU5uEIpHIctP7q1oNqX27tLTPdoY1ht7gJ/x9IUL7lqTDsY7nRW7PrO3sNwzT1NCDIeAC2K/k7WCdrEKk3oj4C3Eqykho6X7tx+lfd2eTN6bzAcekCSseezE=
  gem: coltrane
  on:
    repo: pedrozath/coltrane
notifications:
  slack:
    secure: A4qliXrG8AgvMi9skLwfTfGgRxeVRBIBS8O6tIF2k0oLn+i0XRCEPWYnK4Xa1YufgCnMTFlGA144sxsvuf3spBuwCJkOefA7YhJJVhKQTCpmkSq0IPEaF8+KpwESI1W1hBJuEWmCAxwL1Z+tZa7CON2ELyKgHukxEtUTfQsbXMY1eeISRm7a73xi4DlfTM4UEV2Cfd/Rg9cpP4QGsWANowDsaNm33aQ611BIokfVSZtKf7A4IPAthZOrXkGqD0R4FjUxbDUtQEd5gg3tpcPmWrHIxunlvJow/XBXtv+/qDlbo8LzUUxtkElcGjj1g3hsQEZmevoNxZdGW/8/F5DMMLYYQRfph7Ot9Xm6dNYj3rIUcHjNob1qUNb0ON2pko4gcO6HiU8VZ/oQUsUtBBrB7ddf1htXVdO3jHH2josFTCWgFCzPwgxsCuyP71lieDBolyaKFOyWGaWj6cZhqGUfkSosLZNyDoUEWERkImOHyqvi5TQaPVteZvUeCDkD6ZtCTyEjZI8zXdyPKKweBLxRuGMjUgpsA5QEyo3dlIguLe7OYCLWyYYmEcF+2QjYLevEBFNM1rl6tK8VEF6aost0pa6Rq6/VHRNEEKn0ejYTqbiPGljmOiDOwWSCxQWhlJ9tw692wnpLN5/y0Cda40PQ87hi1tXyvcvLrrvETfYfXcU=
